print("Take 2 float values to add, subtract, multiply and divide them and print their fractional representation.")
num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
sum = float(num1)+float(num2)
print("Sum of two number is ", sum)
sub = float(num1) - float(num2)
print("Sub of two number is", sub)
multi = float(num1) * float(num2)
print("Multi of two number is ", multi)
div = float(num1) / float(num2)
print("Div of two number is ", div)

print("Take 5 float values as input and print the min and max of them all.")
num1 = input("Enter first number: ")
num2 = input("Enter second number: ")
num3 = input("Enter third number: ")
num4 = input("Enter fourth number: ")
num5 = input("Enter fifth number: ")
a = float(min(num1, num2, num3, num4, num5))
print("Min value:", a)
b = float(max(num1, num2, num3, num4, num5))
print("Max value:", b)

print("Print your name in uppercase, lowercase and titlecase.")
c = input("Enter your name: ")
print(c.upper())
print(c.lower())
print(c.title())
